version: '2'

# should we add hostname to dockerfile

services:

  solr:
    image: lukecampbell/docker-ckan-solr
    container_name: solr
    volumes:
      - solr_core_data:/opt/solr/example/solr

  postgis:
    image: mdillon/postgis:9.3
    container_name: postgis
    # Override these in a production environment
    env_file: env
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:3.0.7-alpine
    container_name: redis
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  ckan:
    image: iocas/catalog-docker-ckan:v1
    container_name: iocas_ckan
    env_file: env
    ports:
      - "8080:8080"

  harvester:
    image: ioos/catalog-docker-ckan-harvest:latest
    container_name: harvester
    env_file: env

  pycsw:
    image: ioos/catalog-docker-pycsw:latest
    container_name: ioos-pycsw
    env_file: env
    ports:
      - "8081:8080"

  waf:
    image: lukecampbell/docker-waf
    container_name: iocas_waf
    volumes:
      - "./waf_data:/usr/share/nginx/html/waf"
    ports:
      - "3001:80"

volumes:
  solr_core_data:
    external:
      name: solr_core_data

  pg_data:
    external:
      name: pg_data
 
  redis_data:
  waf_data:
